version = 0.1

[default]
[default.global.parameters]
stack_name = "bank-transfer-lambda-service"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
stack_name = "bank-transfer-default"
s3_prefix = "bank-transfer-default"
region = "us-east-2"
disable_rollback = true
parameter_overrides = ""  # Removed hardcoded overrides
image_repositories = []

[dev.deploy.parameters]
stack_name = "bank-transfer-dev"
s3_prefix = "bank-transfer-dev"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
confirm_changeset = true
disable_rollback = true
parameter_overrides = ""  # Removed hardcoded overrides

[staging.deploy.parameters]
stack_name = "bank-transfer-staging"
s3_prefix = "bank-transfer-staging"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
confirm_changeset = true
disable_rollback = true
parameter_overrides = ""  # Removed hardcoded overrides

[prod.deploy.parameters]
stack_name = "bank-transfer-prod"
s3_prefix = "bank-transfer-prod"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
confirm_changeset = true
disable_rollback = true
parameter_overrides = ""  # Removed hardcoded overrides
