AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
    banktransfer-lamda-service
    Sample SAM Template for bank-transfer-lamda-service

Globals:
    Function:
        Timeout: 5
        Tracing: Active
        LoggingConfig:
            LogFormat: JSON
        Environment:
            Variables:
                WalletHmacKey: !Ref WalletHmacKey
                RequeryEndpoint: !Ref RequeryEndpoint
                RequeryQueueArn: !Ref RequeryQueueArn

Parameters:
    WalletHmacKey:
        Type: AWS::SSM::Parameter::Value<String>
        Default: /wallet/hmacKey
    RequeryEndpoint:
        Type: AWS::SSM::Parameter::Value<String>
        Default: /payment/RequeryQueueUrl
    RequeryQueueArn:
        Type: AWS::SSM::Parameter::Value<String>
        Default: /payment/RequeryQueueArn

Resources:
    RequeryFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/
            Handler: functions/transferRequery.handler
            Runtime: nodejs18.x
            Role: !GetAtt RequeryFunctionRole.Arn
            Architectures:
                - x86_64
            Events:
                SQSEvent:
                    Type: SQS
                    Properties:
                        !Ref RequeryQueueArn
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                Sourcemap: true
                EntryPoints:
                    - functions/transferRequery.ts

    RequeryFunctionRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                          Service: lambda.amazonaws.com
                      Action: "sts:AssumeRole"
            Policies:
                - PolicyName: LambdaBasicExecutionPolicy
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                          - Effect: Allow
                            Action:
                                - "logs:CreateLogGroup"
                                - "logs:CreateLogStream"
                                - "logs:PutLogEvents"
                                - "sqs:SendMessage"
                                - "sqs:GetQueueAttributes"
                                - "sqs:ReceiveMessage"
                                - "sqs:DeleteMessage"
                            Resource: "*"

Outputs:
    RequeryFunction:
        Description: Requery Service
        Value: !GetAtt RequeryFunction.Arn
    HelloWorldFunctionIamRole:
        Description: Implicit IAM Role created for Transfer Requery function
        Value: !GetAtt RequeryFunctionRole.Arn
