AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
    banktransfer-lamda-service
    Sample SAM Template for bank-transfer-lamda-service

Globals:
    Function:
        Timeout: 5
        Tracing: Active
        LoggingConfig:
            LogFormat: JSON
        Environment:
            Variables:
                WalletHmacKey: !Ref WalletHmacKey
                BASEURL: !Ref BASEURL
                TransferRequeryQueueArn: !Ref TransferRequeryQueueArn
                TransferRequeryQueueUrl: !Ref TransferRequeryQueueUrl
                SubnetId: !Ref SubnetId
                SecurityGroupId: !Ref SecurityGroupId

Parameters:
    WalletHmacKey:
        Type: AWS::SSM::Parameter::Value<String>
    BASEURL:
        Type: AWS::SSM::Parameter::Value<String>
    TransferRequeryQueueArn:
        Type: AWS::SSM::Parameter::Value<String>
    TransferRequeryQueueUrl:
        Type: AWS::SSM::Parameter::Value<String>
    SubnetId:
        Type: AWS::SSM::Parameter::Value<String>
    SecurityGroupId:
        Type: AWS::SSM::Parameter::Value<String>

Resources:
    TransferRequeryFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/
            Handler: functions/transferRequery.handler
            Runtime: nodejs18.x
            Role: !GetAtt TransferRequeryFunctionRole.Arn
            Architectures:
                - x86_64
            Events:
                SQSEvent:
                    Type: SQS
                    Properties:
                        Queue: !Ref TransferRequeryQueueArn
            VpcConfig:
                SecurityGroupIds:
                  - !Ref SecurityGroupId  
                SubnetIds:
                  - !Ref SubnetId
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                Sourcemap: true
                EntryPoints:
                    - functions/transferRequery.ts

    TransferRequeryFunctionRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                          Service: lambda.amazonaws.com
                      Action: "sts:AssumeRole"
            Policies:
                - PolicyName: LambdaBasicExecutionPolicy
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                          - Effect: Allow
                            Action:
                                - "logs:CreateLogGroup"
                                - "logs:CreateLogStream"
                                - "logs:PutLogEvents"
                                - "sqs:SendMessage"
                                - "sqs:GetQueueAttributes"
                                - "sqs:ReceiveMessage"
                                - "sqs:DeleteMessage"
                            Resource: "*"
                - PolicyName: LambdaVpcPolicy
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                          - Effect: Allow
                            Action:
                                 - "ec2:CreateNetworkInterface"
                                 - "ec2:DescribeNetworkInterfaces"
                                 - "ec2:DeleteNetworkInterface"
                            Resource: "*"

Outputs:
    TransferRequeryFunction:
        Description: TransferRequery Service
        Value: !GetAtt TransferRequeryFunction.Arn
    TransferRequeryFunctionRole:
        Description: Implicit IAM Role created for Transfer TransferRequery function
        Value: !GetAtt TransferRequeryFunctionRole.Arn
